# Generated by Django 3.1.3 on 2020-11-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201119_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='applicant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='money',
            name='recommend',
            field=models.IntegerField(default=0),
        ),
    ]
