# Generated by Django 3.1.3 on 2020-11-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201119_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='applicant',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='recommend',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, null=True),
        ),
    ]
