# Generated by Django 3.1.3 on 2020-11-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201119_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='applicant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='money',
            name='recommend',
            field=models.IntegerField(),
        ),
    ]
